print message if installer failed
git-svn-id: https://formic.svn.sourceforge.net/svnroot/formic/trunk@199 1a7380c6-1923-0410-bcea-c2eae4ba7d6c

diff --git a/src/resources/selfextract b/src/resources/selfextract
--- a/src/resources/selfextract
+++ b/src/resources/selfextract
@@ -22,10 +22,15 @@ else
   ./formic ${formic.action} $@
 fi
 
+EXIT_CODE=$?
+
 # delete the temp files
 cd $PREV
 rm -rf $WRKDIR
 
-exit 0
+if [ $EXIT_CODE -gt 0 ]; then
+  echo "Installer failed.  See /tmp/install.log for details."
+fi
+exit $EXIT_CODE
 
 __BEGIN_ARCHIVE__
